spring:
  profiles: prod
spring:
  datasource:
    url: jdbc:postgresql://postgres-event:5432/event_service
    driverClassName: org.postgresql.Driver
    username: ${EVENT_DB_USERNAME:event}
    password: ${EVENT_DB_PASSWORD:password}
