server:
  port: 8085
  forward-headers-strategy: framework

spring:
  application:
    name: 'payment-service'

razorpay:
  key_id: ${RAZORPAYa_KEY_ID}
  key_secret: ${RAZORPAY_KEY_SECRET}
  webhook:
    secret: ${RAZORPAY_WEBHOOK_SECRET} # 7A+so2UBjF3AALPPcmbkaG3ZR7SX/bIkePMDJ3FN4zI=
    event_type: ${RAZORPAY_WEBHOOK_EVENT_TYPE}
    