spring:
  datasource:
    url: jdbc:mysql://mysql-user:3306/user_service
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${USER_DB_USERNAME:user}
    password: ${USER_DB_PASSWORD:password}
jwt:
  secret: ${JWT_SECRET}
