spring:
  datasource:
    url: jdbc:mysql://mysql-search-qa:3306/search_service_qa
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${SEARCH_DB_USERNAME:search}
    password: ${SEARCH_DB_PASSWORD:password}
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
search:
  mode: external
  elasticsearch:
    host: ${SEARCH_ES_HOST:elasticsearch}
    port: ${SEARCH_ES_PORT:9200}
