server:
  port: 8083
  forward-headers-strategy: framework

spring:
  application:
    name: inventory-service
  
jwt:
  secret: ${JWT_SECRET:82a3beb52b097b3fab2628cb35162a4c767833a91c257a16f6ec69de88b98284}
